### ISSUE TITLE
BUG: Unsupport HTTP 1.1 routine

### ISSUE THREAD

**Issue by a-petelin** [dmerkushov/nanoservices#5]
**Describe the bug**
Nanoservices with enabled HTTP don't support correct behavior for HTTP v1.1 as sended in response header

**To Reproduce**
0. Enable HTTP in config
1. Start nanoservice
2. Open browser on other PC
3. Send call to nanoservice via HTTP
4. Got various error messages (depends of method for send call)

**Expected behavior**
Data sended from nanoservice avaible in browser

**Logs**

**Environment**
 - Astra Linux 1.6
 - gcc 5.4.0 20160609

**Comment by dmerkushov** [comment]
Fixed by #18
